### ISSUE TITLE
New square randomly poping up outside the board

### ISSUE THREAD

**Issue by Lloople** [Lloople/vue-snake#2]
Food generation sometimes creates a new square outside the main board

**Comment by madhupolu** [comment]
@Lloople, shall I work on it? and can you please add a screenshot of that sporadic issue?

**Comment by Lloople** [comment]
Thank you for your interest! Yeah sure take a look if you want to 🙂.

Unfortunately, I cannot reproduce this bug for a while since it's totally random. The issue is that the new food appears outside the game board, so it's impossible to eat it.

If you want to try it before anything else, you can play it at snake.davidllop.com
