### ISSUE TITLE
Fix play again button

### ISSUE THREAD

**Issue by Lloople** [Lloople/vue-snake#5]
After the game is over, if you try to play again using the button that resets everything it does not work as expected.

- Last food remains on the board.
- New snake appears in the correct position, but the previous one is still in the board.
- New snake cannot move, this could be because it's using the previous snake head instead of the new one.

**Comment by luceleaftea** [comment]
Hey!  Found this through Hacktoberfest, I'm willing to take a look at this!  I'm starting to use Vue at work so this is perfect for learning more as well :)

**Comment by Lloople** [comment]
Awesome! Really appreciate that 🙏
