### ISSUE TITLE
Play sounds instantly

### ISSUE THREAD

**Issue by Lloople** [Lloople/vue-snake#6]
There are three sounds related to actions in the game, but they play with some lag. It's downloading them each time.

So, if possible, the game should download the 3 wav files just when loading the page, and consume them for every action without downloading again.

**Comment by marfgold1** [comment]
How about add each <audio> in the html with preload="auto" and have refs to them so in playSound() you can just get the refs and play the audio?

**Comment by Nopraz** [comment]
Hi, i would like to work on that !
