### ISSUE TITLE
Play button plays startup sound while game is running

### ISSUE THREAD

**Issue by luceleaftea** [Lloople/vue-snake#9]
I tried hitting the button while the game was running to see what would happen.  It didn't reset anything which seems great, but it did play the sound like it's starting up again.  If that sound should be disabled that's a really quick fix.  However, if you do want a sound playing for UX feedback, I'd suggest playing a different, more "error-y" sound to indicate the button isn't working right now (which would match up with the button changing it's style during play).

Alternative solutions:
- Don't even let the user click on the button during play (make the button actually disabled while the game is running)
- Change the Play button to a Stop button during gameplay

**Comment by Lloople** [comment]
I like the first solution you proposed. You can ide the button completely if you want, or marking it as disabled until the game is over 👍
